// Copyright 2026 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type CrawlDetalhesDetalhesFiiItem struct {
	Markdown   json.RawMessage `json:"markdown"`
	StatusCode int             `json:"status_code"`
}

type CrawlListarFiisItem struct {
	Markdown   json.RawMessage `json:"markdown"`
	StatusCode int             `json:"status_code"`
	Tables     json.RawMessage `json:"tables"`
}

type FII struct {
	AluguelM2     string `json:"aluguel_m2"`
	CapRate       string `json:"cap_rate"`
	Cotacao       string `json:"cotacao"`
	DividendYield string `json:"dividend_yield"`
	FfoYield      string `json:"ffo_yield"`
	Liquidez      string `json:"liquidez"`
	Papel         string `json:"papel"`
	PrecoM2       string `json:"preco_m2"`
	Pvp           string `json:"pvp"`
	QtdImoveis    string `json:"qtd_imoveis"`
	Segmento      string `json:"segmento"`
	VacanciaMedia string `json:"vacancia_media"`
	ValorMercado  string `json:"valor_mercado"`
}

type FIIListResponse struct {
	Data json.RawMessage `json:"data"`
}
