// Copyright 2026 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"fundamentus-fii-pp-cli/internal/cliutil"
	"github.com/spf13/cobra"
)

func newCrawlDetalhesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPapel string
	var bodyPriority int
	var bodyUrls string

	cmd := &cobra.Command{
		Use:         "crawl-detalhes",
		Short:       "Obtém os detalhes completos de um FII (informações financeiras, imóveis, histórico)",
		Long:        "Obtém os detalhes completos de um FII (informações financeiras, imóveis, histórico)",
		Example:     "  fundamentus-fii-pp-cli crawl-detalhes --papel example-value",
		Annotations: map[string]string{"pp:endpoint": "crawl-detalhes.detalhes-fii", "pp:method": "POST", "pp:path": "/crawl-detalhes"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("papel") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "papel")
			}
			if !cmd.Flags().Changed("urls") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "urls")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/crawl-detalhes"
			params := map[string]string{}
			if flagPapel != "" {
				params["papel"] = formatCLIParamValue(flagPapel)
			}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyPriority != 0 {
				body["priority"] = bodyPriority
			}
			if bodyUrls != "" {
				body["urls"] = cliutil.SplitCSV(bodyUrls)
			}
			data, _, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPapel, "papel", "", "Código do FII (ex: HGLG11, KNRI11, XPLG11)")
	cmd.Flags().IntVar(&bodyPriority, "priority", 10, "Priority")
	cmd.Flags().StringVar(&bodyUrls, "urls", "", "URL do detalhe do FII no Fundamentus (gerado automaticamente pelo parâmetro papel)")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
