// Copyright 2026 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"fundamentus-fii-pp-cli/internal/cliutil"
	"github.com/spf13/cobra"
)

func newCrawlPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyCrawlerConfigHeadersUserAgent string
	var bodyPriority int
	var bodyUrls string

	cmd := &cobra.Command{
		Use:         "crawl",
		Short:       "Obtém a tabela completa de Fundos Imobiliários com todos os indicadores via Crawl4AI",
		Long:        "Obtém a tabela completa de Fundos Imobiliários com todos os indicadores via Crawl4AI",
		Example:     "  fundamentus-fii-pp-cli crawl",
		Annotations: map[string]string{"pp:endpoint": "crawl.listar-fiis", "pp:method": "POST", "pp:path": "/crawl"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("urls") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "urls")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/crawl"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			{
				nestedCrawlerConfig := map[string]any{}
				{
					nestedCrawlerConfigHeaders := map[string]any{}
					if bodyCrawlerConfigHeadersUserAgent != "" {
						nestedCrawlerConfigHeaders["User-Agent"] = bodyCrawlerConfigHeadersUserAgent
					}
					if len(nestedCrawlerConfigHeaders) > 0 {
						nestedCrawlerConfig["headers"] = nestedCrawlerConfigHeaders
					}
				}
				if len(nestedCrawlerConfig) > 0 {
					body["crawler_config"] = nestedCrawlerConfig
				}
			}
			if bodyPriority != 0 {
				body["priority"] = bodyPriority
			}
			if bodyUrls != "" {
				body["urls"] = cliutil.SplitCSV(bodyUrls)
			}
			data, _, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}

			// Tenta extrair tabela estruturada do JSON do Crawl4AI.
			// O Crawl4AI retorna dados no formato:
			//   {"success":true,"results":[{"tables":[{"headers":[...],"rows":[[...],...]}]}]}
			// Extraímos as linhas e usamos o pipeline de output existente.
			if IsCrawl4AITableResponse(data) {
				items, parseErr := ExtractFiiTableRows(data)
				if parseErr == nil && len(items) > 0 {
					if wantsHumanTable(cmd.OutOrStdout(), flags) {
						if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
							return err
						}
						fmt.Fprintf(os.Stderr, "\nShowing %d FIIs. Use --select to choose columns, --json for JSON output.\n", len(items))
						return nil
					}
					// Para --json/--agent, emite os dados estruturados
					out, _ := json.MarshalIndent(items, "", "  ")
					fmt.Fprintln(cmd.OutOrStdout(), string(out))
					return nil
				}
			}

			// Fallback: output raw do Crawl4AI (HTML, etc.)
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyCrawlerConfigHeadersUserAgent, "crawler-config-headers-user-agent", "", "User agent")
	cmd.Flags().IntVar(&bodyPriority, "priority", 10, "Priority")
	cmd.Flags().StringVar(&bodyUrls, "urls", "", "Urls")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
